### ISSUE TITLE
Add convenience functions for common package() actions

### ISSUE THREAD

**Issue by JamiKettunen** [Arsen6331/lure#39] opened 2022-11-20 01:51 UTC
I'm familiar with [Void's `xbps-src` and the package build `template`s](https://github.com/void-linux/void-packages/blob/master/Manual.md#global-functions) and thought the following would be neat over here as well and shouldn't be out of scope either :)

Here's a few things that could be done instead of the original lines I see in `lure.sh` files to shrink some of the common actions you'd want to do in a `package()`:

- [x] Binaries (`${pkgdir}/usr/bin`)
  - `install -Dm755 "${srcdir}/${name}/build/admc" "${pkgdir}/usr/bin/admc"`
  `install_bin "${srcdir}/${name}/build/admc"`
    - second arg for changing install target filename, e.g. `install_bin Espanso-X11.AppImage espanso`
    - without any args `install_bin` could set source file to just `${name}`? not sure if this makes sense, maybe if enough packages essentially would repeat `install_bin ${name}` basically
    - see Void's `vbin`

- [x] Systemd user services (`${pkgdir}/usr/lib/systemd/user`)
  - `install -Dm644 "systemd.service" "${pkgdir}/usr/lib/systemd/user/espanso.service"`
  `install_systemd_user systemd.service espanso.service`
    - second arg for changing install target filename
    - see Void's `vsv`

- [x] Systemd services (`${pkgdir}/usr/lib/systemd/system`)
  - `install -Dm644 "${srcdir}/syncthing-relaysrv.service" "${pkgdir}/usr/lib/systemd/system/syncthing-relaysrv.service"`
  `install_systemd "${srcdir}/syncthing-relaysrv.service"`
    - second arg for changing install target filename
    - see Void's `vsv`

- [x] Config files (`${pkgdir}/etc`)
  - `install -Dm644 "./itd.toml" ${pkgdir}/etc/itd.toml`
  `install_conf itd.toml`
    - second arg for changing install target filename?
    - see Void's `vconf`

- [x] License files (`${pkgdir}/usr/share/licenses/${name}`)
  - `install -Dm644 "./LICENSE" "${pkgdir}/usr/share/licenses/itd/LICENSE"`
  `install_license LICENSE`
  - without any args `install_license` could set source file to just `LICENSE`?
  - see Void's `vlicense`

- [x] Shell completions (for `bash`, `zsh` and `fish`)
  - `./k9s completion bash | install -Dm644 /dev/stdin "$pkgdir/usr/share/bash-completion/completion/k9s"`
  `install_completion "./k9s completion bash" bash k9s`
  - `./k9s completion zsh | install -Dm644 /dev/stdin "$pkgdir/usr/share/zsh/site-functions/_k9s"`
  `install_completion "./k9s completion zsh" zsh k9s`
  - `./k9s completion fish | install -Dm644 /dev/stdin "$pkgdir/usr/share/fish/vendor_completions.d/k9s.fish"`
  `install_completion "./k9s completion fish" fish k9s`
  - first arg would either be file to install (has to exist) or a command to generate the completions which will be installed from `/dev/stdin`
  - without third arg `install_completion` could set command to install completions for to just `${name}`?
  - see Void's `vcompletion`

- [x] Manual pages (`${pkgdir}/usr/share/man`)
  - `install -Dm644 man/strelaysrv.1 "${pkgdir}/usr/share/man/man1/${name}.1"`
  `install_man man/strelaysrv.1`
  - see Void's `vman`

- [x] Desktop files (`${pkgdir}/usr/share/applications`)
  - `install -Dm644 "${srcdir}/${name}/share/admc.desktop" "${pkgdir}/usr/share/applications/admc.desktop"`
  `install_desktop "${srcdir}/${name}/share/admc.desktop"`
    - second arg for changing install target filename?

- [x] Libraries (`${pkgdir}/usr/lib`)
  - `install -Dm644 "${srcdir}/${name}/build/libadldap.so" "${pkgdir}/usr/lib/libadldap.so"`
  `install_lib "${srcdir}/${name}/build/libadldap.so"`
  
  A lot of these could just be one-liner `bash` functions that are included before running `package` function, for example:
  ```sh
  install_bin() { install -Dm0755 "$1" -t "${pkgdir}/usr/bin/${2:-${1//*\/}}"; }
  ```
  Thoughts?

**Comment by Arsen6331** [comment] 2022-11-20 01:54
I think this is a really good idea

**Comment by Arsen6331** [comment] 2022-11-21 04:28
I looked over this again and read it completely. I agree with most of it, though I do think hyphens would be better for the command names than underscores.

There is one that will be a bit more complex. Specifically, it's the `install_library`. The problem is that different distros install libraries in different locations. For example, Arch puts everything in `/usr/lib`. Fedora has `/usr/lib64` for 64-bit libraries. Debian as always completely disregards all conventions and creates a completely separate folder inside `/usr/lib` called `x86_64-linux-gnu` or whatever your architecture is, and then installs them there.

**Comment by Arsen6331** [comment] 2022-11-21 04:37
What I can try to do is read the output of `ldconfig` to see what paths `ld.so` searches, then put it into one of those, but ideally, I'd want to place it in an appropriate directory, and `ldconfig`'s output will also include `/usr/local` paths and paths for the incorrect architecture.

**Comment by Arsen6331** [comment] 2022-11-21 04:55
I've added the following functions:

- `install-bin`
- `install-systemd-user`
- `install-systemd`
- `install-config`
- `install-license`
- `install-manual`
- `install-desktop`

They are implemented on the Go side in `helpers.go` because writing the functions in bash would be a massive pain with this library.

I will add `install-completion` next, and then think about what to do about the libraries being in different places.

**Comment by Arsen6331** [comment] 2022-11-21 04:56
Actually, now that I think about it, `install-bin` should be `install-binary` to match the verbosity of the other names

**Comment by Arsen6331** [comment] 2022-11-21 04:57
Done, I just changed it to `install-binary`.

**Comment by JamiKettunen** [comment] 2022-11-21 10:04
Hm interesting looks like dashes in function names are a `bash` extension (which is fine here as the `lure.sh` scripts use that as interpreter with arrays and such anyway) and is why I've personally avoided them, just hadn't thought about that in a while ^^

As for the libraries in different places that's even more reason for the wrapper function to be added; if no better way is found maybe we could just make `/usr/lib` the default (same as the `lure.sh` scripts such as [`admc`](https://github.com/Arsen6331/lure-repo/blob/e29a62d/admc/lure.sh#L32) use it already) and add configurable distro overrides for each of the target locations in e.g. the `manager/*.go` files, or even better make it dependent on the reported `os-release` `ID` / `ID_LIKE` with a mapping to the expected library paths somewhere.

Since it might have to be e.g. `/usr/lib64` I guess there should be an env var for e.g. `WORDSIZE` with `32` or `64` being the possible values, the `/usr/lib/x86_64-linux-gnu` or whatever might be more annoying as we'll have to know the target triple, though I believe e.g. `gcc` should report that somewhere at least if there's no other way (could also make yet another table in `manager/*.go` from architectures to triples, but eh...).

**Comment by Arsen6331** [comment] 2022-11-21 10:09
Another possibility is to use a custom library directory like `/usr/lib/lure` and add an `ld.so` config to LURE so that the system linker look there automatically.

**Comment by JamiKettunen** [comment] 2022-11-21 10:16
Sounds like a possible solution, not sure if that route would be affected in particular but we should keep in mind that the final solution should also work on [musl libc](https://musl.libc.org/) as this is what [Alpine Linux](https://www.alpinelinux.org/) for example uses (Void also can use musl instead of glibc but that's not supported yet in general anyway).

**Comment by Arsen6331** [comment] 2022-11-21 10:18
Yeah, I just thought of that issue as well. It does seem that musl has a similar mechanism. From the musl libc documentation:

> If installing for the first time and using dynamic linking, it may be necessary to create a path file for the dynamic linker. See ../etc/ld-musl-$(ARCH).path under the heading Additional Files Used later in this part of the manual.

**Comment by Arsen6331** [comment] 2022-11-21 10:20
What can also be done is that if the `/etc/ld.so.conf.d` directory doesn't exist, we just fall back to `/usr/lib`.

**Comment by JamiKettunen** [comment] 2022-11-21 10:40
Hm actually on Void musl `/etc/ld.so.conf.d/lib32.conf` still exists along with `/usr/lib32/locale` with both coming from [`base-files`](https://github.com/void-linux/void-packages/tree/master/srcpkgs/base-files), that probably needs to be addressed upstream as those should be considered glibc artifacts.

**Comment by Arsen6331** [comment] 2022-11-21 23:21
Just added `install-completion` in e22bc0f

**Comment by JamiKettunen** [comment] 2022-11-21 23:46
I took a look at [the `install-manual` implementation](https://github.com/Arsen6331/lure/blob/e22bc0f/helpers.go#L22) and it's not quite proper; it should install to `/usr/share/man/man<X>` where `<X>` is the number at the end of the filename, e.g. with `strelaysrv.1` it's `1` but with `mdoc.7` it's `7`

**Comment by Arsen6331** [comment] 2022-11-21 23:54
Ah, ok, I'll add a custom implementation for that then, should be pretty easy.

**Comment by Arsen6331** [comment] 2022-11-22 05:47
I've added the `install-library` using the approach I mentioned above in f30f4c7. I added a map for all the Debian multiarch tuples that Go supports, and a variable that allows users to override the lib dir. Do you think this is adequate or should it be changed?

**Comment by JamiKettunen** [comment] 2022-11-22 12:56
I'm not sure, but I'm at least also aware of [Chimera Linux](https://chimera-linux.org/) (`ID="chimera"`) which uses `/usr/lib` along with [`apk-tools`](https://git.alpinelinux.org/apk-tools/) package manager + musl libc similar to Alpine so it should already work with `lure` in general.

**Comment by Arsen6331** [comment] 2022-11-22 16:58
Alright, I already have exceptions for Arch, Alpine, and Void (for when nFPM gains support for it eventually). I can just add Chimera.

**Comment by Arsen6331** [comment] 2022-11-22 17:08
While I don't particularly like the fact that there will have to be a list of exceptions, I can't think of any other way that I'd be able to handle cross-packaging reliably.

**Comment by JamiKettunen** [comment] 2022-11-22 17:17
Maybe the exception list could be somehow made an array like the following (I think that's valid go? didn't compile check)
```go
usrLibDistros := [...]string{"alpine", "arch", "chimera", "void"}
```
and the code refactored so it doesn't require adding a new if case `distroID == "new_distro_id" || slices.Contains(distroLike, "new_distro_id")` every time, though if the size of the exceptions list starts getting out of hand maybe something else will have to be figured out anyway

**Comment by Arsen6331** [comment] 2022-11-22 17:20
Yeah, I was going to do just that, though I'd probably make it a slice instead of an array (remove the `...`)

**Comment by Arsen6331** [comment] 2022-11-22 19:44
Done in 3ca052f

**Comment by JamiKettunen** [comment] 2022-11-22 19:57
Unless I missed something I believe everything in this issue is now implemented; let's get a new tag sometime and start using these in  [lure-repo](https://github.com/Arsen6331/lure-repo) (and maybe update CI to hint people trying to use e.g. `install -Dm755 "${srcdir}/${name}/build/admc" "${pkgdir}/usr/bin/admc"` about the existance of them) ^^

**Comment by JamiKettunen** [comment] 2022-11-22 19:58
There could be a problem with updating repos with these new `lure` tool features so I wonder if it would be worth it to add some hint about the minimum supported `lure` version to the repo files it fetches?

**Comment by Arsen6331** [comment] 2022-11-22 20:03
> Unless I missed something I believe everything in this issue is now implemented

Yes, I think everything is now implemented. I am going to write documentation for this, then close the issue. Then I think I can tag a new release.

In order to hint people about their existence, I'll have to update https://github.com/Arsen6331/lure-repo-bot. It will be a bit complex since I'll have to look through users' actual code, not just the variables, but I think it can be done.

> There could be a problem with updating repos with these new lure tool features so I wonder if it would be worth it to add some hint about the minimum supported lure version to the repo files it fetches

That's probably a good idea for the future, but obviously, people with current versions won't be able to see any warnings generated by that because the code is not there yet.

I also think the `lure-{git,bin}` packages in the LURE repo shouldn't use these for a while because I know some people use those to update LURE.

**Comment by Arsen6331** [comment] 2022-11-22 20:27
Documentation added in 3361358. I'll close this issue now, add a mechanism for checking the minimum supported version of a repo, and then tag a release.

**Closed** 2022-11-22 20:27 UTC
Labels: enhancement

**Comment by Arsen6331** [comment] 2022-11-22 21:13
New release is out: https://gitea.arsenm.dev/Arsen6331/lure/releases/tag/v0.0.4
